/**
 * Report Types
 * Type definitions for Report operations
 * Schema: id(auto), title, reason, description, created_at
 */

import { ReportReason } from "@/prisma/index";

export interface CreateReportRequest {
    title: string;
    report_tag_id: number[];
    description: string;
    // id will be auto-generated by @default(autoincrement())
}

export interface CreateReportResponse {
    success: boolean;
    message: string;
    report?: any; // Use any for now since Prisma returns the actual model
}

export interface GetReportsResponse {
    success: boolean;
    reports: any[]; // Use any[] for now since Prisma returns the actual model
    pagination?: {
        current_page: number;
        total_pages: number;
        total_records: number;
        per_page: number;
    };
}

export interface UpdateReportRequest {
    title?: string;
    description?: string;
    report_tag_id?: number[];
}

export interface ReportFilters {
    id?: number; // filter by specific report ID
    title?: string; // search by title
    reason?: string; // filter by reason
    page?: number;
    limit?: number;
}

export interface ReportStatsResponse {
    success: boolean;
    stats: {
        total_reports: number;
        // Simplified stats for simple schema without user/blog relations
    };
}