# Cloud Build configuration for Development environment
# Triggered manually from main branch

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:latest'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:dev'
      - '.'

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_ARTIFACT_REGISTRY}/${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--quiet'
    waitFor: ['push-image']

  # Step 4: Run database migrations (optional)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Migrations will be run automatically on container startup"
        echo "Check Cloud Run logs for migration status"
    waitFor: ['deploy-cloud-run']

# Substitutions (passed from Terraform)
substitutions:
  _ENVIRONMENT: 'dev'
  _REGION: 'asia-southeast1'
  _SERVICE_NAME: 'sigma-hawk-tua-backend-dev'
  _ARTIFACT_REGISTRY: 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/sigma-hawk-tua-backend-repo-dev'
  _IMAGE_NAME: 'sigma-hawk-tua-backend'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'  # 20 minutes
